### ISSUE TITLE
使用bazel编译yacl发生错误

### ISSUE THREAD

**Issue by lgs2513** [secretflow/yacl#148]
lgs@dell-Precision-7920-Tower:/data/lgs/yinyu/yacl$ bazel build //... -c dbg
Starting local Bazel server and connecting to it...
INFO: Analyzed 195 targets (117 packages loaded, 9791 targets configured).
INFO: Found 195 targets...

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.UnsupportedOperationException: /data/lgs/yinyu/yacl/bazel-bin (??????)
at com.google.devtools.build.lib.unix.NativePosixFiles.symlink(Native Method)
at com.google.devtools.build.lib.unix.UnixFileSystem.createSymbolicLink(UnixFileSystem.java:344)
at com.google.devtools.build.lib.vfs.Path.createSymbolicLink(Path.java:500)
at com.google.devtools.build.lib.vfs.FileSystemUtils.ensureSymbolicLink(FileSystemUtils.java:343)
at com.google.devtools.build.lib.vfs.FileSystemUtils.ensureSymbolicLink(FileSystemUtils.java:294)
at com.google.devtools.build.lib.buildtool.OutputDirectoryLinksUtils.createLink(OutputDirectoryLinksUtils.java:332)
at com.google.devtools.build.lib.buildtool.OutputDirectoryLinksUtils.createOutputDirectoryLinks(OutputDirectoryLinksUtils.java:143)
at com.google.devtools.build.lib.buildtool.ExecutionTool.createConvenienceSymlinks(ExecutionTool.java:695)
at com.google.devtools.build.lib.buildtool.ExecutionTool.handleConvenienceSymlinks(ExecutionTool.java:654)
at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:363)
at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:235)
at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:443)
at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:411)
at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:103)
at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
at io.grpc.Context$1.run(Context.java:579)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
lgs@dell-Precision-7920-Tower:/data/lgs/yinyu/yacl$

满足requirements的安装要求，但是报错，编译不成功

**Comment by Jamie-Cui** [comment]
可以贴一下 bazel 的版本吗？谢谢～

**Comment by lgs2513** [comment]
> 可以贴一下 bazel 的版本吗？谢谢～



> 可以贴一下 bazel 的版本吗？谢谢～

使用的spu库搭建时requirements中的6.2.1版本

**Comment by Jamie-Cui** [comment]
Bazel 一般情况应该不太会 crash 的 ... 可以额外贴一下下面两个信息嘛？
1. OS 版本
2. GCC 版本

**Comment by lgs2513** [comment]
> Bazel 一般情况应该不太会 crash 的 ... 可以额外贴一下下面两个信息嘛？
> 
> 1. OS 版本
> 2. GCC 版本
ubuntu20.04；gcc是按照spu配的

**Comment by anakinxc** [comment]
看起来是 create symlink /data/lgs/yinyu/yacl/bazel-bin 的时候 bazel 炸了。。。你这个文件夹所在的 fs 有啥特殊的吗

**Comment by lgs2513** [comment]
> 看起来是 create symlink /data/lgs/yinyu/yacl/bazel-bin 的时候 bazel 炸了。。。你这个文件夹所在的 fs 有啥特殊的吗

请问fs是什么？是文件权限吗？

**Comment by lgs2513** [comment]
> > > 看起来是 create symlink /data/lgs/yinyu/yacl/bazel-bin 的时候 bazel 炸了。。。你这个文件夹所在的 fs 有啥特殊的吗
> > 
> > 
> > 请问fs是什么？是文件权限吗？
> 
> 就整个 filesystem，包括权限，有什么特殊的吗。。 或者你也可以 ls 一下看看 bazel-bin 这个文件有没有，有的话先删了看看

好，谢谢
