### ISSUE TITLE
building bug after run 'bazel build //yacl/...'

### ISSUE THREAD

**Issue by 2646jx** [secretflow/yacl#422]
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupDataN{actionLookupKey=ConfiguredTargetKey{label=@@com_github_google_benchmark//:benchmark, config=BuildConfigurationKey[37b3921117ac061a749349ab24dee630faf9fbb9a4c674d487a9c4a9974d7f6f]}, actionIndex=10}' (requested by nodes 'ArtifactNestedSetKey[19]@1123876094')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: com.google.devtools.build.lib.rules.apple.DottedVersion$InvalidDottedVersionException: Dotted version components must all start with the form \d+([a-z0-9]*?)?(\d+)? but got 'None'

**Comment by tongke6** [comment]
@2646jx Please provide the build environment information, such as the operating system details, whether it's Docker or a physical machine, the YACL version, etc.

**Comment by 2646jx** [comment]
Thanks for you reply. I'm running on MacOS M2. I didn't run with docker.

**Comment by Jamie-Cui** [comment]
Can you try cleanup with bazel cache with commands bazel clean --expunge and then rebuild with bazel build //yacl/... again?

**Comment by tongke6** [comment]
It looks very similar to [this issue](https://github.com/bazelbuild/bazel/issues/23111)
try running bazel clean --expunge after installing Xcode

**Comment by tongke6** [comment]
Please follow the steps if you want to build on MacOS : https://github.com/secretflow/yacl/blob/main/GETTING_STARTED.md#macos

**Comment by 2646jx** [comment]
Okay, I'll give it a try and then check it again.
